MIN_LENGTH_GESTURE = 5
NEXT_STEP_COUNT = 2
ROW_LENGTH = 400
COL_LENGTH = 400
THRESHOLDOFREALGESTURE = 4.6
MAX_MEM = 100
GAP_THRESS = 1.5
GAP_THRES_INTERNAL = 0.9
NO_GAP_COUNT_THRESS = 2
CONTINUOUS_1 = 5
CONTINUOUS_2 =10
CONTINUOUS_3 =20

EXAMPLAR_FILE = "examplar"